var app = new Vue({
  el: "#app",
  data: {
    screenHeight: 0, //当前屏幕的高度
    scrollTop: 0, // 滚动条当前的位置
    arr: [
      "2020",
      "2021.10.10.广告名片",
      "2021.10.24.鼠标跟随",
      "2021.11.13.选项卡",
      "2021.11.21鼠标视差滚轮响应",
      "2021.12.19.圣诞树",
      "2021.6.27.Css键盘",
      "2021.7.25.360度全景图",
      "2021.9.12.侧边导航栏",
      "2022.3.27.鼠标悬停方向感应名片",
      "32-place-item-center",
      "34-drag-drop-api",
      "3dCard",
      "3D折叠效果",
      "3D排版",
      "3D旋转",
      "3D旋转-魔方",
      "3D旋转星球模型",
      "3D翻牌",
      "3D翻转",
      "404-1",
      "43-css-gradient-shadow",
      "book",
      "Canvas光束光线爆炸特效",
      "ClipTransition",
      "clock",
      "CSS3时钟效果",
      "CSS鹦鹉",
      "douyin",
      "egg",
      "file_manager",
      "H5粒子时间+弹跳小球",
      "hjiaoben84",
      "iphone",
      "iPhone12页面卷动逐行滑入效果",
      "iPhone镂空动画",
      "jianzhi",
      "jiaoben5961",
      "jiaoben6024",
      "JS口袋妖怪列表选择交互",
      "light",
      "LightOff",
      "line-font",
      "loading",
      "login",
      "login-3D旋转",
      "login2",
      "login3",
      "login5",
      "login6",
      "page-404",
      "polaroid",
      "pxLineBg",
      "shaolei",
      "slider",
      "split",
      "split-font",
      "svg-animation-truck",
      "svg_animation",
      "svg_text_animation",
      "svg文字",
      "switch-button",
      "todo-list",
      "wave",
      "wushiyin",
      "yijiansanlian",
      "五星红旗",
      "刮刮乐",
      "卡片-简历",
      "响应式导航栏",
      "多款炫酷鼠标悬停图文动画效果",
      "导航条",
      "导航栏3D",
      "打字机",
      "技能条",
      "拉伸和透明",
      "按钮",
      "按钮-q弹",
      "按钮-五彩",
      "按钮-故障风",
      "按钮特效20种",
      "搜索框1",
      "新拟态-指纹按钮",
      "新拟态-播放器",
      "新拟态-选项卡",
      "新拟态-按钮组",
      "新拟态UI",
      "新拟态指纹按钮",
      "新拟态计算机",
      "柱状图",
      "水滴融合",
      "浮动文字",
      "漂亮的input输入框",
      "瀑布流",
      "瀑布流-图片",
      "瀑布流-页面滑动",
      "瀑布流3",
      "瀑布流布局",
      "火焰文字",
      "百叶窗",
      "粒子特效",
      "纯CSS3图片滤镜效果",
      "纯CSS3花瓣旋转加载动画",
      "翻页漫画",
      "视差滚动",
      "视差滚动2",
      "视差滚动3",
      "视差滚动6",
      "轮播图",
      "轮播图-3D",
      "轮播图-纯CSS轮",
      "轮播图-高级切换、",
      "轮播图2",
      "轮播图3",
      "输入框-动态",
      "选项卡-高级",
      "闪光文字",
      "黑金卡片",
    ],
  },
  methods: {
    //滚动事件
    handleScroll() {
      this.scrollTop =
        window.pageYOffset ||
        document.documentElement.scrollTop ||
        document.body.scrollTop;
    },
  },
  mounted() {
    this.screenHeight = window.screen.height;
    console.log("页面高度", window.screen.height);
    // 向页面添加滚动事件
    window.addEventListener("scroll", this.handleScroll, true);
  },
  destroyed() {
    //离开这个界面之后，删除滚动事件，不然容易除bug
    window.removeEventListener("scroll", this.handleScroll);
  },
});
